config/routes.rb
Rails.application.routes.draw do

  resources :itineraries do
    resources :destinations
  end

  root to: "itineraries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord

  belongs_to :itinerary
  
  geocoded_by :address
  
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if results.first.address.present? && geo = results.first
      obj.address_line_1, obj.address_line_2 = geo.address.split(",")
      obj.city    = geo.city
      obj.post_code = geo.postal_code
    end
  end

  validates :address_line_1,   presence: true

  validates :city, presence: true

  validates :duration_in_minutes, presence: true,
                                  numericality: { greater_than_or_equal_to: 0}

  validates :index, presence: true,
                    numericality: { greater_than_or_equal_to: 0},
                    uniqueness: {scope: :itinerary_id}

  validates :itinerary, presence: true

  validates :latitude, presence: true

  validates :longitude, presence: true

  validates :post_code, presence: true

  validate :validate_is_in_london?

  # Geocode the address, unless the lat / lng has already changed
  before_validation :geocode, if:  Proc.new { has_address_changed? },
                              unless: Proc.new {  have_coordinates_changed? }

  # Reverse Geocode any coordinates that have been manually set                                          
  before_validation :reverse_geocode, if: Proc.new { have_coordinates_changed? }



  before_save :set_times

  def address
      [address_line_1, address_line_2, city, post_code].compact.join(', ')
  end

  

  def set_times
    
    return unless itinerary.present?
    
    # If we have a destation before this one..
    if previous_destination = itinerary.destinations.where("index < ?", index).first

      # Lookup the previous destinations information as the departure information
      previous_departure_time = previous_destination.departure_time || Time.now
      previous_coordinates = [previous_destination.latitude, previous_destination.longitude]

    # If this is the first destination, then use the office and route start time  
    else 
      previous_departure_time = itinerary.start_at
      previous_coordinates = [ 51.5246515, -0.0852404]
    end

    next_coordinates = [latitude, longitude]

    self.travel_time_in_minutes = CityMapper.new.travel_time(previous_departure_time, previous_coordinates, next_coordinates)

    if self.travel_time_in_minutes
      self.arrival_time = (travel_time_in_minutes).minutes.since(previous_departure_time)
      self.departure_time = arrival_time + duration_in_minutes
    end

  end

  private

  def validate_is_in_london?
    return unless latitude.present? && longitude.present? 

    distance_to_london = self.distance_to([51.507351, -0.127758])
    errors.add(:post_code, "cannot be outside London") if distance_to_london > 25
  end

  def has_address_changed?
    changes_to_save.include?("address_line_1") || 
    changes_to_save.include?("address_line_2") || 
    changes_to_save.include?("city") ||
    changes_to_save.include?("post_code")
  end

  def have_coordinates_changed?
    changes_to_save.include?("latitude")  
    changes_to_save.include?("longitude") 
  end

  

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    
    has_many :destinations, :dependent => :destroy

    validates :agent_name, presence: true

    validates :start_at, presence: true

    validate :validate_start_at
    
    after_initialize :set_defaults

    after_save :update_destinations, if:  Proc.new { has_start_at_changed? }

    # TODO: Should require at least 1 destination
    
    def end_at
        self.destinations.maximum(:departure_time)
    end

    def update_destinations
        self.destinations.order(:index).each do |destination|
            destination.set_times
            destination.save
        end
    end

    private 



    # On initialization, sets a default start time and place.
    def set_defaults
    
        
     
        self.start_at ||= 1.hour.since

        if self.destinations.empty?
            self.destinations.new(latitude:  51.5246515, longitude: -0.0852404, post_code: "EC2A 4QS", index: 0, duration_in_minutes: 0, departure_time: self.start_at, arrival_time: self.start_at, travel_time_in_minutes: 0 )
        end
    end

    # Validates that the start time is in the future
    def validate_start_at
        errors.add(:start_at, "can't be in the past") if start_at.present? && start_at < Time.now
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_action :find_itinerary

  def index
    @destinations = @itinerary.destinations.order(:index)
  end

  def new
    @destinations = @itinerary.destinations
    @destination = @itinerary.destinations.new
  end

  def create
    @destination = @itinerary.destinations.new(destination_params)
    @destination.index = @itinerary.destinations.maximum(:index) + 1

    if @destination.save
      redirect_to new_itinerary_destination_path(@itinerary)
      flash[:notice] = "Itinerary has been successfuly created"
    else
      redirect_to new_itinerary_destination_path(@itinerary)
      flash[:alert] = "Itinerary has not been created"
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
  end


  def update
    @destination = @itinerary.destinations.find(params[:id])
    @destination.update(destination_params)
    redirect_to new_itinerary_destination_path(@itinerary)
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])

    if @itinerary.destroy
      redirect_to itineraries_path
      flash[:notice] = "Itinerary has been successfuly destroyed"
    else
      redirect_to itineraries_path
      flash[:alert] = "Itinerary has been successfuly destroyed"
    end
  end

  protected

  def find_itinerary
    @itinerary = Itinerary.find(params[:itinerary_id])
  end

  def destination_params
    params.require(:destination).permit(:address_line_1, :address_line_2, :city, :post_code, :duration_in_minutes)
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def index
    @itineraries = Itinerary.all
  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)

    if @itinerary.save
      redirect_to new_itinerary_destination_path(@itinerary)
      flash[:notice] = "Itinerary has been successfuly created"
    else
      redirect_to new_itinerary_path
      flash[:alert] = "Itinerary has not been created"
    end
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(itinerary_params)
    redirect_to new_itinerary_destination_path(@itinerary)
  end


  def destroy
    @itinerary = Itinerary.find(params[:id])

    if @itinerary.destroy
      redirect_to itineraries_path
      flash[:notice] = "Itinerary has been successfuly destroyed"
    else
      redirect_to itineraries_path
      flash[:alert] = "Itinerary has been successfuly destroyed"
    end
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:agent_name, :start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/_destination_list_item.html.erb
<li>
    <% if destination_list_item.travel_time_in_minutes.present? &&  destination_list_item.travel_time_in_minutes > 0 %>
        <div class="travel-time">
            <p>
                <strong><%=destination_list_item.travel_time_in_minutes%></strong> minutes
            </p>
        </div>
    <% end %>
    
    <div class="arrival">
        <p>Arrive at: <span><%=destination_list_item.arrival_time.to_formatted_s(:time) %></span></p>
    </div>

    <div class="info">
            <h3><%=destination_list_item.address_line_1%></h3>
            <%=destination_list_item.address_line_2%><br/>
            <%=destination_list_item.city%><br/>
            <%=destination_list_item.post_code%>
    </div>

    <div class="arrival">
        <p>Depart at: <span><%=destination_list_item.departure_time.to_formatted_s(:time) %></span></p>
    </div>
    
</li>

app/views/destinations/create.html.erb
<h1>Destinations#create</h1>
<p>Find me in app/views/destinations/create.html.erb</p>

app/views/destinations/destroy.html.erb
<h1>Destinations#destroy</h1>
<p>Find me in app/views/destinations/destroy.html.erb</p>

app/views/destinations/edit.html.erb
<h1>Destinations#edit</h1>
<p>Find me in app/views/destinations/edit.html.erb</p>

app/views/destinations/index.html.erb
<h1>Destinations#index</h1>
<p>Find me in app/views/destinations/index.html.erb</p>

app/views/destinations/new.html.erb
<section style="width: 400px; float: left;">
    <h2>Itinary</h2>

    <%=form_for(@itinerary) do |f| %>
        <div class="form">
            <%=render partial:"itineraries/itinerary", locals: {f: f} %>

            <%=f.submit "Update" %>
        </div>
    <% end %>

    <h3>Add Destination</h3>

    
        <%=form_for [@itinerary, @destination] do |f| %>
        <div class="form">
            <div>
                <%=f.label :address_line_1 %>
                <%=f.text_field :address_line_1 %>
            </div>
                <div>
                <%=f.label :address_line_2 %>
                <%=f.text_field :address_line_2 %>
            </div>
                <div>
                <%=f.label :city %>
                <%=f.text_field :city %>
            </div>
                <div>
                <%=f.label :post_code %>
                <%=f.text_field :post_code %>
            </div>

            <div>
                <%=f.label :duration_in_minutes %>
                <%=f.text_field :duration_in_minutes %>
            </div>

            <%=f.submit %>
            </div>
        <% end %>
    
</section>

<section class="column" style="margin-left: 100px;float: left">
    <h3>Destinations</h3>

    <ul class="destination-list">
        <%= render partial: "destination_list_item", collection: @destinations.slice(0 , @destinations.length - 1) %>
    </ul>
</section>

app/views/destinations/update.html.erb
<h1>Destinations#update</h1>
<p>Find me in app/views/destinations/update.html.erb</p>

app/views/itineraries/_itinerary.html.erb
    <div>
        <%=f.label :agent_name %>
        <%=f.text_field :agent_name %>
    </div>

    <div>
        <%=f.label :start_at %>
        <%=f.datetime_select :start_at %>
    </div>

app/views/itineraries/_itinerary_list_item.html.erb
<li>
    <div class="itinerary_list_item">
        <div class="index">#<%=itinerary_list_item.id%></div>
        <div class="info">
            <h3><%=itinerary_list_item.agent_name%></h3>
            <p>
                Start: <%=itinerary_list_item.start_at.to_formatted_s(:long_ordinal)%> <br/>
                End: <%=itinerary_list_item.end_at.to_formatted_s(:long_ordinal)%></p>
            <p><%=itinerary_list_item.destinations.count%> destinations</p>
        </div>
        <div class="actions">
            <%=link_to "Edit", new_itinerary_destination_path(itinerary_list_item) %><br/>
            <%=link_to "Delete", itinerary_path(itinerary_list_item), method: 'delete' %> 
        </div>

    </div>
</li>

app/views/itineraries/create.html.erb
<h1>Itineraries#create</h1>
<p>Find me in app/views/itineraries/create.html.erb</p>

app/views/itineraries/destroy.html.erb
<h1>Itineraries#destroy</h1>
<p>Find me in app/views/itineraries/destroy.html.erb</p>

app/views/itineraries/edit.html.erb
<h1>Itineraries#edit</h1>
<p>Find me in app/views/itineraries/edit.html.erb</p>

app/views/itineraries/index.html.erb
<h2>Itineraries (<%=link_to "New", new_itinerary_path%>)</h2>

    
<ul class="itineraries-list">
    <% if @itineraries.present? %>
        <%=render partial: "itinerary_list_item", collection: @itineraries %>
    <% else %>
        <li>No itineraries found</li>
    <% end %>    
</ul>

app/views/itineraries/new.html.erb
<h1>Create itineraries</h1>

<%=form_for @itinerary do |f| %>

    <%=render partial: "itinerary", locals: {f: f} %>

    <%=f.submit %>
<% end %>

app/views/itineraries/update.html.erb
<h1>Itineraries#update</h1>
<p>Find me in app/views/itineraries/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Time Travel</h1>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>